### ISSUE TITLE
v0.31: no newmigration api. How can I "Modify the database" in "Working With Genie Apps: Intermediate Topics"

### ISSUE THREAD

**Issue by deahhh** [GenieFramework/Genie.jl#235] opened 2020-05-24 03:28 UTC

**Comment by essenciary** [comment] 2020-05-26 08:10
What do you have in mind? Can you give me some examples? 

We have create/drop table, create/drop column, create/drop index.

**Comment by deahhh** [comment] 2020-05-27 02:54
> What do you have in mind? Can you give me some examples?
> 
> We have create/drop table, create/drop column, create/drop index.

Thank you! "newmigration" has been replaced by create/drop function? That's grate! The trouble I met is just "no variable newmigration" when I tried "Working With Genie Apps: Intermediate Topics" ->"Uploading files"->"Modify the database"->"julia> Genie.newmigration("add cover column")".

I found in Internet that this API exists in version 0.26.

**Comment by MLackner** [comment] 2020-05-27 13:29
I have the same problem. I tried to circumvent it by running
```julia
julia> SearchLight.Migration.new("add cover column")
```
I don't know if this is the intended way of doing migrations now. The problem is that this creates a migration file with spaces (`*_add cover column`) and subsequently the migration file starts with `module Add cover column` and thus throwing an error.

Running
```julia
julia> SearchLight.Migration.new("add_cover_column")
```
with underscores works for creating a proper migrations file but I can't add columns. This is because the `SearchLightSQLite.add_column` method tries to run the `SearchLight.column` method, which doesn't exist and I have no idea where it moved.

**Comment by essenciary** [comment] 2020-05-27 14:44
Thanks @MLackner - there's been some massive refactoring in SearchLight lately and it seems some things broke. It definitely sounds like a bug, it should generate correct file names. 

Let me check,, thanks for the PR!

**Comment by essenciary** [comment] 2020-05-27 16:30
Thanks - I merged the PR and patched the MySQL adapter which had the same problem. Let's see about the wrong names.

**Comment by essenciary** [comment] 2020-05-27 17:08
Indeed, `remove_column` seems to have been lost in translation - it's present in the MySQL and Postgres adapters, but not for SQLite.

**Comment by essenciary** [comment] 2020-05-27 17:18
OK, I found it 

```julia
function remove_column_sql(table_name::String, name::String) :: Nothing
  throw(SearchLight.UnsupportedException(:remove_column, Symbol(DB_ADAPTER)))
end
```

Basically it's because SQLite does not support the operation so it's not implemented. I'll update the docs.

**Comment by essenciary** [comment] 2020-05-27 17:58
Looks like the real issue is that the tutorial hasn't been updated in a long time. The proper way to do it now is: 
```julia
julia> SearchLight.Generator.newmigration("add cover column")
[ Info: 2020-05-27 19:56:56 New migration created at C:\Dropbox\Projects\MyGenieApp\db\migrations\2020052717565635_add_cover_column.jl
```
Seems to work great.

**Comment by essenciary** [comment] 2020-05-27 18:21
OK, I updated the docs - I don't have a lot of time but I addressed what seemed obviously incorrect. Please let me know if anything else is off. 

![image](https://user-images.githubusercontent.com/11292378/83057689-9031c080-a057-11ea-97fc-6baf794a0b1f.png)

**Comment by deahhh** [comment] 2020-05-28 05:35
> OK, I updated the docs - I don't have a lot of time but I addressed what seemed obviously incorrect.

Thank you very much!

**Comment by deahhh** [comment] 2020-05-28 05:43
> I have the same problem. I tried to circumvent it by running
> 
> ```julia
> julia> SearchLight.Migration.new("add cover column")
> ```
> 
> I don't know if this is the intended way of doing migrations now. The problem is that this creates a migration file with spaces (`*_add cover column`) and subsequently the migration file starts with `module Add cover column` and thus throwing an error.
> 
> Running
> 
> ```julia
> julia> SearchLight.Migration.new("add_cover_column")
> ```
> 
> with underscores works for creating a proper migrations file but I can't add columns. This is because the `SearchLightSQLite.add_column` method tries to run the `SearchLight.column` method, which doesn't exist and I have no idea where it moved.
> 
> Edit:
> I created a pull request for this issue: [GenieFramework/SearchLightSQLite.jl#2](https://github.com/GenieFramework/SearchLightSQLite.jl/pull/2)
> Maybe this fix should be applied to the other connectors too.
> 
> There seems also to be a problem in that there is no `remove_column()` method defined in the `SearchLightSQLite` connector.

Thank you very much!
I read the source code of Genie before, but didn't find any function definition named "newmigration"! Do you know where is it?

**Closed** 2020-05-28 05:48 UTC

**Comment by deahhh** [comment] 2020-05-28 05:50
All the problem is I am not familiar with SearchLight and Genie.

**Comment by essenciary** [comment] 2020-05-28 14:21
@deahhh No worries - the code in the docs should now work. If that's not the case, lmk.

**Comment by deahhh** [comment] 2020-05-29 14:41
@essenciary Thanks a lot!

**Comment by deahhh** [comment] 2020-06-05 02:52
@essenciary 
I found one other mistakes: in "function SearchLight.Migration.add_column", "SearchLight.column", should be "SearchLight.Migration.column".

**Comment by essenciary** [comment] 2020-06-05 06:43
@deahhh Great catch, thank you! Registered patch version.
