### ISSUE TITLE
Genie.Assets.assets_config

### ISSUE THREAD

**Issue by GitVking** [GenieFramework/Genie.jl#428] opened 2021-10-31 16:37 UTC
**Describe the bug**
Did you forget to export the function in assets.jl?

**Comment by AbhimanyuAryan** [comment] 2021-10-31 16:41
@GitVking what is breaking? Can you add some extra info? 

- Intended behavior: 

- What you are getting: 

- Genie version:

- Julia version:

- OS:

**Comment by GitVking** [comment] 2021-10-31 17:02
> @GitVking what is breaking? Can you add some extra info? 
> 
> - Intended behavior: 
> 
> - What you are getting: 
> When I test StippleDemos -IrisCluster 
activate.  
instantiate in the project 
and include("Iris...jl") it report
LoadError:UbdefVarError:assets_config! not defined
I read the asset.jl in package Genie, I find there existing that function but it's not exported
> - Genie version:
> v3.3  actually the project require v4 But after I update my Genie. Genie is still v3.3. Same things occur in Stipple, StippleCharts package. 
So I have to alter the dependence.toml file
> - Julia version:
> 1.6.2  1.6.3
> - OS: 
win 10   Mac(Intel)

**Comment by AbhimanyuAryan** [comment] 2021-10-31 17:04
@GitVking Try

```
pkg> add Genie#master 
```

**Comment by GitVking** [comment] 2021-10-31 18:00
> @GitVking Try
> 
> ```
> pkg> add Genie#master 
> ```
> should work

there is something wrong with StippleCharts still, I tried rm Genie, Stipple,StippleUI,StippleCharts first and add them all followed#master
but...
(AdvanceExamples) pkg> instantiate
Updating registry at `C:\Users\16941\.julia\registries\General`
ERROR: Unsatisfiable requirements detected for package StippleCharts [30ddb3f0]:
StippleCharts [30ddb3f0] log:
├─possible versions are: 0.1.0-0.13.0 or uninstalled
└─restricted to versions 0.14 by an explicit requirement — no versions left

The Project.toml require v0.14StippleChart which is already   
satisfied
Why it is so weird, I can't figure out its dependences

**Comment by AbhimanyuAryan** [comment] 2021-10-31 23:57
@GitVking actually we need to tag everything to latest versions and update compat to that 

```
> rm StippleCharts
```

and

```
> add StippleCharts#master
```

**Comment by essenciary** [comment] 2021-11-01 09:33
Yes, good point, I'll register new versions now.

**Comment by AbhimanyuAryan** [comment] 2021-11-01 11:05
@GitVking you can try now. We tagged new version: https://github.com/GenieFramework/Genie.jl/releases/tag/v4.0.0

You can simply say 

```julia
(v1.1) pkg> update
```

to [update](https://docs.julialang.org/en/v1/stdlib/Pkg/) julia package to latest

**Comment by GitVking** [comment] 2021-11-01 11:36
@essenciary 
Hi, some demos's Project.toml also require higher version on Stipple, StippleCharts, StippleUI in StippleDemos 
like this one:
 mac@Vking  ~/work/StippleDemos   master  cd AdvanceExamples
 mac@Vking  ~/work/StippleDemos/AdvanceExamples   master  ll
total 32
-rw-r--r--  1 mac  staff   4.5K 11  1 19:28 MultiUserApp.jl
-rw-r--r--  1 mac  staff   304B 11  1 19:28 Project.toml
-rw-r--r--  1 mac  staff   693B 11  1 19:28 README.md
 mac@Vking  ~/work/StippleDemos/AdvanceExamples   master  julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.2 (2021-07-14)
 _/ |\__'_|_|_|\__'_|  |  Built by Homebrew (v1.6.2_1)
|__/                   |

(@v1.6) pkg> activate .
  Activating environment at `~/work/StippleDemos/AdvanceExamples/Project.toml`

(AdvanceExamples) pkg> instantiate
    Updating registry at `~/.julia/registries/General`
ERROR: Unsatisfiable requirements detected for package StippleCharts [30ddb3f0]:
 StippleCharts [30ddb3f0] log:
 ├─possible versions are: 0.1.0-0.13.0 or uninstalled
 └─restricted to versions 0.14 by an explicit requirement — no versions left

(AdvanceExamples) pkg>

**Comment by essenciary** [comment] 2021-11-18 15:23
I think we can close this, all the packages have been released.

**Closed by essenciary** 2021-11-18 15:23 UTC
