### ISSUE TITLE
Error using controller with the example given

### ISSUE THREAD

**Issue by gcollet** [genieframework/Genie.jl#141] opened 2019-05-23 14:31 UTC
**Describe the bug**
I was following the example given here https://github.com/genieframework/Genie.jl/blob/master/docs/content/Working_with_Genie_apps/index.md

At section #html-views, when I try to view page http://127.0.0.1:8000/bgbooks, I got this error :

> ERROR: function skip_element does not accept keyword arguments

**To Reproduce**
I followed the example so I suppose you can do the same ;-)

**Expected behavior**
I hope the page appears

**Additional context**
output of `julia> versioninfo()`

Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE = auto

output of `pkg> st`
    Status `~/work/Julia/MyGenieApp/Project.toml`
  [c43c736e] Genie v0.9.2 #master (https://github.com/essenciary/Genie.jl)
  [682c06a0] JSON v0.20.0
  [39ec1447] Millboard v0.2.0
  [295af30f] Revise v2.1.4

**Comment by essenciary** [comment] 2019-05-24 07:32
@gcollet Thanks - looks like a duplicate of #139 which should be fixed. I can't reproduce. 
Can you try:
1. `pkg> up` to make sure it's the latest Genie
2. deleting the `build/FlaxViews/` folder 
3. restarting the app

If this doesn't fix it, can you please share the app as a zip file? Thanks!

**Comment by gcollet** [comment] 2019-05-24 08:04
@essenciary Thanks for your help !
I did the 3 steps you proposed but I still get the error.
Here is the zip file
[MyGenieApp.zip](https://github.com/genieframework/Genie.jl/files/3215743/MyGenieApp.zip)

**Comment by gcollet** [comment] 2019-05-24 08:19
I tried to create a new app, just to test the process from beginning and I encountered a new error.
I open a new issue

**Comment by essenciary** [comment] 2019-05-24 17:17
@gcollet Thanks, I commented in the other issue. 

Thanks for uploading the app. Works perfectly on my system. I suspect something is off with the package manager on your side. 

Me trying the app you uploaded: 

```julia
 ~/D/MyGenieApp  julia                                 Fri May 24 19:14:42 2019
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.1) pkg> activate .

(MyGenieApp) pkg> st
    Status `~/Downloads/MyGenieApp/Project.toml`
  [c43c736e] Genie v0.9.2 #master (https://github.com/essenciary/Genie.jl)
  [682c06a0] JSON v0.20.0
  [39ec1447] Millboard v0.2.0
  [295af30f] Revise v2.1.5

(MyGenieApp) pkg> instantiate
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`

(MyGenieApp) pkg> st
    Status `~/Downloads/MyGenieApp/Project.toml`
  [c43c736e] Genie v0.9.2 #master (https://github.com/essenciary/Genie.jl)
  [682c06a0] JSON v0.20.0
  [39ec1447] Millboard v0.2.0
  [295af30f] Revise v2.1.5

(MyGenieApp) pkg>
 ~/D/MyGenieApp  bin/repl                                                28.7s  Fri May 24 19:15:14 2019
 _____         _
|   __|___ ___|_|___
|  |  | -_|   | | -_|
|_____|___|_|_|_|___|

┌ Info:
│ Starting Genie in >> DEV << mode
└
[ Info: Logging to file at /Users/adrian/Downloads/MyGenieApp/log/dev.log
julia> startup()
[ Info: Ready!
2019-05-24 19:15:54:DEBUG:Main: Web Server starting at http://127.0.0.1:8000
2019-05-24 19:15:54:DEBUG:Main: Web Server running at http://127.0.0.1:8000
```

**Comment by essenciary** [comment] 2019-05-31 17:07
I'm closing this - please reopen if the problem persists.

**Closed by essenciary** 2019-05-31 17:07 UTC
