### ISSUE TITLE
MyController not found in current path

### ISSUE THREAD

**Issue by wadehenning** [GenieFramework/Genie.jl#266] opened 2020-08-06 20:27 UTC
### **Issue Context**
I am going through your documentation and creating a Genie Web Service with a controller titled `HypothesisTestController`.  When I attempt to access the Controller, I am getting the error:
`ERROR: ArgumentError: Package HypTestController not found in current path:`
`- Run import Pkg; Pkg.add("HypTestController") to install the HypTestController package.`

NOTE: Initially, everything worked fine.  It was only after modifying the function in the controller a little that the error occurred.

### **My Process**
I created the Web Service using `Genie.newapp_webservice("HypTest")`
I added the controller using `Genie.newcontroller("HypTest")`

I opened the HypTestController.jl file and changed it to:

`module HypTestController `

  `function TestRandom()`
      `return rand(2,2)`
 `end`

`end `

I then tested the module: `using HypTestController` followed by `HypTestController.TestRandom()`, and all checked out.

I added the line `using HypTestController` to my `routes.jl` file and everything was good.  Then, I went back to the `HypTestController.jl` file and added parameters to the function:
 
`module HypTestController `

  `function TestRandom(n)`
      `return rand(n,n)`
 `end`

`end `

Your advice is greatly appreciated.

Now when I try `using HypTestController`, I get the error above.  My working directory looks correct: 
`pwd()`
`/home/henning/DensityTesting` 

Your advice is greatly appreciated.

### Additional Information Update
I deleted the above and started over, creating a new Genie Web Service and Controller.  Here is the output:

***When I created the web service, I got an error in the end***
```julia> Genie.newapp_webservice("HypTesty")
[ Info: Done! New app created at /home/henning/HypTesty
[ Info: Changing active directory to /home/henning/HypTesty
[ Info: Installing app dependencies
.......

Genie v1.1.0
Active env: DEV


Ready! 

ERROR: ArgParse.ArgParseError("too many arguments")
Stacktrace:
 [1] argparse_error(::Any) at /home/henning/.julia/packages/ArgParse/WUIf8/src/parsing.jl:9
....
```
***Then I created a new controller.***
```
julia> Genie.newcontroller("hypothesis")
[ Info: 2020-08-07 12:23:03 New controller created at /home/henning/HypTesty/app/resources/hypothesis/HypothesisController.jl
```
***But I can not access the controller.***
```
julia> using HypothesisController
[ Info: 2020-08-07 12:24:28 Precompiling HypothesisController [top-level]
ERROR: IOError: stream is closed or unusable
Stacktrace:
 [1] check_open at ./stream.jl:328 [inlined]
 [2] uv_write_async(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:959
 [3] uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:922
 [4] unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:1005
 [5] write at ./strings/io.jl:183 [inlined]
 [6] write_transport_layer(::Base.PipeEndpoint, ::String) at /home/henning/.vscode/extensions/julialang.language-julia-1.0.2/scripts/packages/JSONRPC/src/core.jl:68
 [7] macro expansion at /home/henning/.vscode/extensions/julialang.language-julia-1.0.2/scripts/packages/JSONRPC/src/core.jl:94 [inlined]
 [8] (::VSCodeServer.JSONRPC.var"#1#3"{VSCodeServer.JSONRPC.JSONRPCEndpoint})() at ./task.jl:356
ERROR: KeyError: key HypothesisController [top-level] not found
Stacktrace:
 [1] getindex at ./dict.jl:467 [inlined]
 [2] root_module at ./loading.jl:968 [inlined]
 [3] require(::Base.PkgId) at ./loading.jl:934
 [4] require(::Module, ::Symbol) at ./loading.jl:923
 [5] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```
***Try to access the controller again***
```
julia> using HypothesisController
┌ Warning: 2020-08-07 12:25:47 Replacing module `HypothesesController`
└ @ Base loading.jl:948
ERROR: KeyError: key HypothesisController [top-level] not found
Stacktrace:
 [1] getindex at ./dict.jl:467 [inlined]
 [2] root_module at ./loading.jl:968 [inlined]
 [3] require(::Base.PkgId) at ./loading.jl:934
 [4] require(::Module, ::Symbol) at ./loading.jl:923
 [5] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```

**Comment by essenciary** [comment] 2020-08-07 20:17
That `ERROR: ArgParse.ArgParseError("too many arguments")` does not look good. 

Please provide the information requested in the issue template (versioninfo, pkg status).

**Comment by wadehenning** [comment] 2020-08-07 20:36
Thanks for the feedback-- the issue template did not appear when I created this issue and I could not remember the commands to get this information.

```julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "/usr/share/code/code"
  JULIA_NUM_THREADS = 
  JULIA_REVISE = auto

```

```(HypTesty) pkg> status
Status `~/HypTesty/Project.toml`
  [c43c736e] Genie v1.1.0
  [e6f89c97] LoggingExtras v0.4.2
  [739be429] MbedTLS v1.0.2
  [295af30f] Revise v2.7.3


```

**Comment by essenciary** [comment] 2020-08-20 07:49
Thanks for the info. Sorry for the delay, I've been traveling. Did you manage it get it working yet?

**Comment by wadehenning** [comment] 2020-08-20 11:38
@essenciary -- I just put it off to the side.  I thought I would try building or reinstalling the package and trying again.  I'll let you know how that goes.

**Comment by wadehenning** [comment] 2020-09-27 12:43
@essenciary   I finally have time to get back to this work;  I must be doing something foolish, I can not see what, but I have learned more:
**the  Controller does work when I call it in my GNOME terminal** 
```julia> Genie.newcontroller("MyController")
[ Info: New controller created at /home/henning/juliaProjects/MyGenieApp/app/resources/mycontroller/MyControllerController.jl

julia> using MyControllerController
[ Info: Precompiling MyControllerController [top-level]

julia> MyControllerController.returnrand()
3×3 Array{Float64,2}:
 0.107561  0.169036  0.830897
 0.295636  0.214937  0.0570599
 0.643622  0.987249  0.751688


julia> pwd()
"/home/henning/juliaProjects/MyGenieApp"

```

 **but I get an error in VS Code** 
```
julia> pwd()
"/home/henning/juliaProjects/MyGenieApp"

julia> using MyControllerController
ERROR: ArgumentError: Package MyControllerController not found in current path:
- Run `import Pkg; Pkg.add("MyControllerController")` to install the MyControllerController package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:893
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```

**Comment by essenciary** [comment] 2020-09-27 16:59
@wadehenning What exactly are you doing in VS Code? What are the steps I should take to reproduce the error?

**Comment by wadehenning** [comment] 2020-09-27 23:18
@essenciary For me, this works in the `GNOME` terminal but not in the VS Code terminal.  I guess something with VS Code, but I don't have any other issues that I know of.  I must be going crazy.

```
using Genie
```
```
Genie.newapp("App")
```
***change directory to App root***

```
Genie.newcontroller("Test")
```
```
using TestController
```

**Comment by wadehenning** [comment] 2020-09-30 10:32
@essenciary If I go back to my old laptop using Julia 1.4.1, an older VS Code (v1.44.2) and  Genie v0.31.1 it works.  Maybe is something strange on my development computer. I'll keep tinkering with it, but I am under a deadline and might have to walk away for a bit again back to the less fancy solution that I have been using.
Thanks for your help.  This is an exciting package and I appreciate the work your team is doing.

**Comment by wadehenning** [comment] 2020-09-30 12:39
@essenciary I went through the process above on my development computer and got no error.  Who knows.  Thanks.

**Comment by wadehenning** [comment] 2020-10-01 10:10
@essenciary .  It did work in the moment but it seems I am still missing some understanding.  What do you think about this--  I can see my `FuncsController.jl` file in my path, but I can't `using` it:

```
julia> pwd()
"/home/henning/juliaProjects/NormaRao/app/resources/funcs"

julia> readdir()
1-element Array{String,1}:
 "FuncsController.jl"

julia> using FuncsController
ERROR: ArgumentError: Package FuncsController not found in current path:
- Run `import Pkg; Pkg.add("FuncsController")` to install the FuncsController package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:893
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088

```

**Contents of FuncsController.jl**

```
module FuncsController
  # Build something great
  export x, y

  x() = "x"
  y() = "y"
  p() = "p"
  
end
```

**Comment by essenciary** [comment] 2020-10-02 09:05
@wadehenning How are you starting/loading the Genie app? A full stack Genie app needs to be bootstrapped in order to address things like this (activate the Pkg environment, add files to the load path, etc). You can either use the scripts in the `bin/` folder (eg `bin/repl` to start up a "Genie repl" or load it manually (when in the root folder of the app run `julia> using Genie` and `julia> Genie.loadapp()`). This will set up the whole environment and the controllers will be found. 

More details here: 
https://genieframework.github.io/Genie.jl/dev/tutorials/10--Loading_Genie_Apps.html

**Comment by essenciary** [comment] 2020-11-24 13:09
Closing this as it seems to be a user issue with loading/bootstrapping Genie apps. Please feel free to reopen if you have more info.

**Closed by essenciary** 2020-11-24 13:09 UTC
